title: Multimodal Language Learning
email: ""
permalink: /:title/
description: >- # this means to ignore newlines until "baseurl:"
  Multimodal Language Learning.
baseurl: "/Comics-Viewer" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

